### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [ryanlsmith4/contractor_proj#1]
Great job, @ryanlsmith4!

Please make the following edits to pass this project by EOD today and close this ticket:

* Include the deployed Heroku link in your `README`
* Make sure `main.handlebars` uses Bootstrap 4 (as in the requirements) instead of 3.3.7

Thanks!
-d

**Comment by ryanlsmith4** [comment]
Alright Updated with boot strap 4 and added readme with heroku link!
